# Generated by Django 4.2.3 on 2024-07-31 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_alter_garage_phone_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garage',
            name='phone',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=12),
        ),
    ]
