# Generated by Django 4.2.3 on 2024-08-03 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_booking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
