# Generated by Django 4.2.3 on 2024-08-22 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0004_vehicle'),
    ]

    operations = [
        migrations.CreateModel(
            name='GarageProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=100)),
                ('exact_location', models.TextField()),
                ('image', models.ImageField(upload_to='garage_profile_images/')),
                ('garage_policies', models.TextField()),
                ('garage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='car.garage')),
            ],
        ),
    ]
