# Generated by Django 4.2.3 on 2024-08-04 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0005_booking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
