# Generated by Django 4.2.3 on 2024-08-22 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0005_garageprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='garageprofile',
            name='image',
        ),
    ]
