# Generated by Django 4.2.3 on 2024-08-05 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0007_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='slot',
            field=models.CharField(max_length=30),
        ),
    ]
