# Generated by Django 4.2.3 on 2024-08-07 05:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0010_alter_booking_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('garage_name', models.CharField(max_length=255)),
                ('user_name', models.CharField(max_length=255)),
                ('date_booked', models.DateField()),
                ('slot_booked', models.CharField(max_length=30)),
                ('date_of_booking', models.DateTimeField(default=django.utils.timezone.now)),
                ('service_selected', models.CharField(max_length=255)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('card_number', models.CharField(max_length=16)),
                ('cvv', models.CharField(max_length=3)),
                ('admin_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
    ]
