# Generated by Django 4.2.3 on 2024-08-07 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0011_bookinghistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinghistory',
            name='total_amount',
            field=models.CharField(max_length=60),
        ),
    ]
