# Generated by Django 4.2.3 on 2024-08-07 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0012_alter_bookinghistory_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinghistory',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
